### ISSUE TITLE
Expose additional configuration options

### ISSUE THREAD

**Issue by bfclarke** [PMBio/deeprvat#131]
There are configuration options hard-coded in `deeprvat/deeprvat/base_configurations.yaml` that are currently not supported in `deeprvat_input_config.yaml` but should be exposed (with current hard-coded values as defaults):
```
#DeepRVAT model training settings
training:
    train_proportion: 0.8
    n_parallel_jobs: 6
    dataloader_config:
        batch_size: 1024
        num_workers: 0
        temp_dir: $TMPDIR/deeprvat_train

#DeepRVAT model settings
model:
    type: DeepSet
    config:
        phi_layers: 2
        phi_hidden_dim: 20
        rho_layers: 3
        rho_hidden_dim: 10
        activation: LeakyReLU
        pool: max
        use_sigmoid: True
        metrics:
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}

#Training dataset settings
training_data:
    dataloader_config:
        batch_size: 64
        num_workers: 8

#Association dataset settings
association_testing_data:
    dataloader_config:
        batch_size: 16
        num_workers: 10

#Additional settings for association testing
n_burden_chunks: 5
n_regression_chunks: 2
n_avg_chunks: 1
```
