### ISSUE TITLE
MAF thresholds above 0.01 won't work

### ISSUE THREAD

**Issue by bfclarke** [PMBio/deeprvat#132]
Setting a MAF threshold above 0.01 for `*_data_thresholds` in `deeprvat_input_config.yaml` won't work because of the below lines in base_configurations.yaml, which don't get updated when the full config is generated.
```
training_data:
    dataset_config:
        min_common_af:
            MAF: 0.01

association_testing_data:
    dataset_config:
        min_common_af:
            MAF: 0.01
```
