### ISSUE TITLE
Example directory

### ISSUE THREAD

**Issue by PaulineTL** [PMBio/deeprvat#162]
Hi,

I am trying to replicate the preprocessing, annotation pipeline, and seed gene discovery with the example file provided on the GitHub in the directory `example/`. Therefore, I have used the vcf `example/preprocess/data/vcf/test_vcf_data_c21_b1.vcf.gz`, which looks like this:

```
##fileformat=VCFv4.2
##source=VCFake 0.1.0
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of Samples With Data">
##contig=<ID=chr21>
##reference=ftp://ftp.example.com/sample.fa
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1)">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth; some reads may have been filtered">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Phased Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  S10000001       S10000002       10000003        10000004        10000005        10000006        10000007            10000008        10000009        10000010
chr21   10413673        .       T       A       .       PASS    .       GT:AD   0/0:10,20       0/0:15,25       0/0:12,18       0/0:22,25       0/0:30,15       0/0:13,17       0/0:40,40   0/0:28,30       0/0:14,18       0/0:10,10
chr21   10413724        .       C       T       .       PASS    .       GT:AD   0/0:20,30       1/0:25,35       0/0:30,40       0/0:35,45       0/0:40,50       0/0:30,35       0/0:45,55   0/0:32,38       0/0:27,33       0/0:20,25
chr21   5033887 .       G       A       .       PASS    .       GT:AD   0/0:40,50       0/1:35,45       0/0:25,30       0/0:20,25       0/0:38,42       0/0:23,27       0/0:35,40           0/0:40,40       0/0:30,30       0/0:25,25
chr21   5035658 .       C       T       .       PASS    .       GT:AD   0/0:30,20       0/0:25,15       0/0:35,30       0/0:40,25       0/0:45,20       0/0:30,15       0/0:28,12           0/0:22,8        0/0:20,10       0/0:15,5
chr21   5038298 .       A       G       .       PASS    .       GT:AD   0/0:40,40       1/0:35,35       0/0:30,30       0/0:25,25       0/0:20,20       0/0:15,15       0/0:10,10           0/0:5,5 0/0:45,45       0/0:50,50
chr21   5038313 .       C       T       .       PASS    .       GT:AD   0/0:20,15       0/0:25,20       0/0:30,25       0/0:35,30       0/0:40,35       0/0:45,40       0/0:50,45           0/0:55,50       0/0:60,55       0/0:65,60
chr21   5051437 .       C       A       .       PASS    .       GT:AD   0/0:30,25       0/1:25,20       1/0:20,15       0/0:15,10       0/0:10,5        0/0:5,0 0/0:0,0 0/0:0,0 0/0:0,0     0/0:0,0
chr21   5051474 .       T       A       .       PASS    .       GT:AD   0/0:20,20       0/0:30,30       0/1:25,25       0/0:35,35       0/0:40,40       0/0:50,50       0/0:45,45           0/0:35,35       0/0:25,25       0/0:20,20
chr21   5052251 .       C       A       .       PASS    .       GT:AD   0/0:30,30       0/0:25,25       0/0:20,20       1/1:15,15       0/0:10,10       0/0:5,5 0/0:0,0 0/0:0,0 0/0:0,0     0/0:0,0
chr21   5053701 .       T       A       .       PASS    .       GT:AD   0/0:20,10       0/0:25,15       0/0:30,20       0/1:35,25       0/0:40,30       0/0:45,35       0/0:50,40           0/0:55,45       0/0:60,50       0/0:65,55
```
My annotations.parquet file is still being processed, and I am encountering some errors during this process. Therefore, during this time I have looked into the seed gene discovery pipelines. According to the documentation, six files are required, **but the annotations.parquet file I am generating doesn't seem to match the other annotations.parquet file and the other files provided in the example directory (which I thought were generated from the test c21 and c22 vcf files).** 

- **annotations.parquet:** The file is very large and contains data for chromosomes 10, 11, and 12, but neither 21 nor 22
- **protein_coding_genes.parquet:** Contains only 275 genes, distributed across multiple chromosomes (e.g., chr2, chr4, chr5, chr9, chr11, chr12, etc)
- **genotypes.h5:** Matrix of size 1000 × 1145
- **variants.parquet:** Contains 20,891 variants across chromosomes 10, 11, 12, 15, 16, 17, 18, 19, 1, 20, 21, 22, 2, 3, 4, 5, 6, 7, 8, and 9
- **phenotypes.parquet:** Contains data for 1000 subjects.

Can you indicate from which VCF file these files were generated? Alternatively, can you provide the five required files corresponding to the same VCF file (ideally from `test_vcf_data_c21_b1.vcf.gz`), so that I can run the seed gene discovery pipeline to check for any issues with my environment?

Thanks!

**Comment by Marcel-Mueck** [comment]
hey Pauline, can you provide the config file you used? 
Regards, Marcel

**Comment by PaulineTL** [comment]
Oh sorry, I made a mistake in my text:

My annotations.parquet file is still being processed, and I am encountering some errors during this process. Therefore, during this time I have looked into the seed gene discovery pipelines. According to the documentation, six files are required, **but the annotations.parquet file I am generating doesn't seem to match the other annotations.parquet file and the other files provided in the example directory (which I thought were generated from the test c21 and c22 vcf files).** 

- annotations.parquet: The file is very large and contains data for chromosomes 10, 11, and 12, but neither 21 nor 22
- protein_coding_genes.parquet: Contains only 275 genes, distributed across multiple chromosomes (e.g., chr2, chr4, chr5, chr9, chr11, chr12, etc)
- genotypes.h5: Matrix of size 1000 × 1145
- variants.parquet: Contains 20,891 variants across chromosomes 10, 11, 12, 15, 16, 17, 18, 19, 1, 20, 21, 22, 2, 3, 4, 5, 6, 7, 8, and 9
- phenotypes.parquet: Contains data for 1000 subjects

Can you provide the **five required files that match together** so that I can run the seed gene discovery pipeline to check for any issues with my environment? Because, so far, from the files I just cited, they doesn't seem to originate from the same input and therefore, I can not run the seed gene discovery..

And this my config file as you asked (`deeprvat_annotation_config.yaml`): 
```
fasta_dir: reference
fasta_file_name: GRCh38.primary_assembly.genome.fa
gtf_file_name: gencode.v44.annotation.gtf.gz
source_variant_file_pattern: test_vcf_data_c{chr}_b{block}
source_variant_file_type: bcf
included_chromosomes: ['21']
annotation_columns_yaml_file: ../config/annotation_colnames_filling_values.yaml
source_variant_dir: ../preprocess/workdir/norm/bcf
anno_tmp_dir: output_dir/annotations/tmp
anno_dir: output_dir/annotations
vep_cache_dir: repo_dir/ensembl-vep/cache/
vep_plugin_dir: repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir: ../..
kipoiveff_repo_dir: repo_dir/kipoi-veff2
faatpipe_repo_dir: repo_dir/faatpipe
vep_repo_dir: repo_dir/ensembl-vep
preprocessing_workdir: ../preprocess/workdir

include_absplice : False

additional_vep_plugin_cmds:
  cadd: CADD,annotation_data/cadd/whole_genome_SNVs.tsv.gz,annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
  spliceAI: SpliceAI,snv=annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz,indel=annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
  primateAI: PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
  condel: Condel,repo_dir/ensembl-vep/Plugin/config/Condel/config,s,2
  alphamissense: AlphaMissense,file=annotation_data/AlphaMissense/AlphaMissense_hg38.tsv.gz
```

Thanks!

**Comment by PaulineTL** [comment]
My **deeprvat_annotation_config.yaml**: 

```
fasta_dir: reference
fasta_file_name: GRCh38.primary_assembly.genome.fa
gtf_file_name: gencode.v44.annotation.gtf.gz
source_variant_file_pattern: test_vcf_data_c{chr}_b{block}
source_variant_file_type: bcf
included_chromosomes: ['21']
annotation_columns_yaml_file: ../config/annotation_colnames_filling_values.yaml
source_variant_dir: ../preprocess/workdir/norm/bcf
anno_tmp_dir: output_dir/annotations/tmp
anno_dir: output_dir/annotations
vep_cache_dir: repo_dir/ensembl-vep/cache/
vep_plugin_dir: repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir: ../..
kipoiveff_repo_dir: repo_dir/kipoi-veff2
faatpipe_repo_dir: repo_dir/faatpipe
vep_repo_dir: repo_dir/ensembl-vep
preprocessing_workdir: ../preprocess/workdir

include_absplice : False

additional_vep_plugin_cmds:
  cadd: CADD,annotation_data/cadd/whole_genome_SNVs.tsv.gz,annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
  spliceAI: SpliceAI,snv=annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz,indel=annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
  primateAI: PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
  condel: Condel,repo_dir/ensembl-vep/Plugin/config/Condel/config,s,2
  alphamissense: AlphaMissense,file=annotation_data/AlphaMissense/AlphaMissense_hg38.tsv.gz

```
