### ISSUE TITLE
Re-running the annotation pipeline

### ISSUE THREAD

**Issue by PaulineTL** [PMBio/deeprvat#164]
Hi,

I have moved all my annotation inputs and outputs from a previous run to another directory. I replaced the inputs with the outputs from the preprocessing pipeline. As a result, `annotations/output_dir` is now empty. 
However, when I run the following command: `snakemake -j 4 -s /work/gr-fe/ptheimer/deepRvat/deeprvat/pipelines/annotations.snakefile --configfile ../config/deeprvat_annotation_config.yaml --use-conda`, it starts with only 15 jobs/rule to execute, as if still "remembers" some files. Then I get an error in the concat_deepSea rule, which I believe is expected since it requires `output_dir/annotations/all_variants.deepSea.parquet` that I don't have because the rule in the annotation that creates is not in the rules to execute. I have removed the directory `.snakemake`, am I missing something?

Thank you in advance!
Pauline
```
job                           count
--------------------------  -------
add_gene_ids                      1
add_ids_deepSea                   1
all                               1
calculate_MAF                     1
calculate_allele_frequency        1
compute_plof_column               1
concat_annotations                1
concat_deepSea                    1
create_gene_id_file               1
deepSea_PCA                       1
filter_by_exon_distance           1
merge_allele_frequency            1
merge_deepsea_pcas                1
omit_absplice                     1
select_rename_fill_columns        1
total                            15
```

PS: What is the purpose of included_chromosome in the config.yaml? Normally, it should process the entire genome and analyze all genes, not chromosome by chromosome, right?

**Comment by Marcel-Mueck** [comment]
Hey Pauline, 
thank you for opening the issue. One reason that would explain this behaviour would be that your `file_stems` variable is empty, so the `file_stem`wildcards are `None`. 
the `file_stems` variable is created [here](https://github.com/PMBio/deeprvat/blob/1a151b9d7156d4900bb4673e31dfe34f10fa6cb9/pipelines/annotations.snakefile#L145)  from the names of the vcf/bcf files in your `source_variant_dir`. The files have to be named in the pattern specified in `source_variant_file_pattern` (NOTE: This pattern should not include the file ending[ `.vcf `, `.bcf` etc ]) Does this pattern match with the file pattern? Maybe you could provide the config file used as well as the filenames of your input bcf files. 
Regards, 
Marcel

**Comment by PaulineTL** [comment]
My config file is the following:

```
fasta_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/reference
fasta_file_name: GRCh38.primary_assembly.genome.fa
gtf_file_name: gencode.v44.annotation.gtf.gz
source_variant_file_pattern: chr{chr}_test
source_variant_file_type: bcf
included_chromosomes: ['4']
annotation_columns_yaml_file: /work/gr-fe/ptheimer/deepRvat/deeprvat/snakemake_run/config/annotation_colnames_filling_values.yaml
source_variant_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/chr4/preprocessing_workdir/norm/bcf
anno_tmp_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/snakemake_run/output_dir/annotations/tmp
anno_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/snakemake_run/output_dir/annotations
vep_cache_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/repo_dir/ensembl-vep/cache/
vep_plugin_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/repo_dir/ensembl-vep/Plugins
deeprvat_repo_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat
kipoiveff_repo_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/repo_dir/kipoi-veff2
faatpipe_repo_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/repo_dir/faatpipe
vep_repo_dir: /work/gr-fe/ptheimer/deepRvat/deeprvat/deeprvat_requirements/annotations/repo_dir/ensembl-vep
preprocessing_workdir: /work/gr-fe/ptheimer/deepRvat/deeprvat/chr4/preprocessing_workdir

additional_vep_plugin_cmds:
  cadd: CADD,annotation_data/cadd/whole_genome_SNVs.tsv.gz,annotation_data/cadd/gnomad.genomes.r3.0.indel.tsv.gz
  spliceAI: SpliceAI,snv=annotation_data/spliceAI/spliceai_scores.raw.snv.hg38.vcf.gz,indel=annotation_data/spliceAI/spliceai_scores.raw.indel.hg38.vcf.gz
  primateAI: PrimateAI,annotation_data/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
  condel: Condel,repo_dir/ensembl-vep/Plugin/config/Condel/config,s,2
  alphamissense: AlphaMissense,file=annotation_data/AlphaMissense/AlphaMissense_hg38.tsv.gz
```

I took the bcf file from your example : `/work/gr-fe/ptheimer/deepRvat/deeprvat/chr4/preprocessing_workdir/norm/bcf/chr4test.bcf`
